### ISSUE TITLE
TypeError: StringMethods.split()

### ISSUE THREAD

**Issue by RicardoGCCR** [EnzoAndree/FastMLST#6]
Hi Enzo!
I hope you are doing well!

Suddently, I am having an issue running FastMLST: 

Could you please help me figure out what is going on?
Thanks in advance, 
Regards, 
Ricardo

error:
#####################################################
$ fastmlst -v 0 Acineto_bau_ref.fa
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/home/rgcruz/miniconda3/envs/bioinfo/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/rgcruz/miniconda3/envs/bioinfo/bin/fastmlst", line 47, in runMLST
    return MLST(genome, cov, ident, sep, header, shcheme)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgcruz/miniconda3/envs/bioinfo/lib/python3.11/site-packages/fastmlst/mlst.py", line 63, in __init__
    self.blast = self.make_blast()
                 ^^^^^^^^^^^^^^^^^
  File "/home/rgcruz/miniconda3/envs/bioinfo/lib/python3.11/site-packages/fastmlst/mlst.py", line 135, in make_blast
    blastfiltred = self.blast_filter(out)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgcruz/miniconda3/envs/bioinfo/lib/python3.11/site-packages/fastmlst/mlst.py", line 161, in blast_filter
    dfblast['sseqid'].str.split('.', 1, expand=True).
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rgcruz/miniconda3/envs/bioinfo/lib/python3.11/site-packages/pandas/core/strings/accessor.py", line 136, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: StringMethods.split() takes from 1 to 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rgcruz/miniconda3/envs/bioinfo/bin/fastmlst", line 161, in <module>
    for result in tqdm(p.imap(runMLST, multipleargs),
  File "/home/rgcruz/miniconda3/envs/bioinfo/lib/python3.11/site-packages/tqdm/std.py", line 1182, in __iter__
    for obj in iterable:
  File "/home/rgcruz/miniconda3/envs/bioinfo/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
TypeError: StringMethods.split() takes from 1 to 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given
############################################################

**Comment by EnzoAndree** [comment]
Hello Ricardo!

Please update fastmlst to version 0.0.16, which is available on Anaconda (anaconda.org/bioconda/fastmlst). This update should resolve the current issue you are experiencing.

**Comment by RicardoGCCR** [comment]
Fantastic! It was solved. Thank you!
